import { Box, styled, Typography } from "@mui/material";
import svg1 from "../assets/certif_1.svg";
import svg2 from "../assets/certif_2.svg";
import svg3 from "../assets/certif_3.svg";

import { BadgeTypeDescription } from "../components/CardType";

const TheBadgeTitle = styled(Typography)(({ theme }) => ({
  color: theme.palette.common.white,
  fontWeight: "700",
  fontSize: "100px",
  textShadow: "6px 4px 4px rgba(0, 0, 0, 0.5)",
}));

const TheBadgeSubTitle = styled(Typography)(({ theme }) => ({
  color: theme.palette.common.white,
  fontWeight: "700",
  fontSize: "64px",
  lineHeight: "85px",
  margin: 0,
}));

const Paragraph = styled(Typography)(({ theme }) => ({
  letterSpacing: "0em",
  textAlign: "left",
  color: theme.palette.common.white,
  fontStyle: "normal",
  fontWeight: "500",
  fontSize: "20px",
  lineHeight: "28px",
  margin: 0,
  marginTop: theme.spacing(2),
  width: "50%",
  [theme.breakpoints.down("md")]: {
    width: "100%",
  },
}));

const TypesTitle = styled(Typography)(({ theme }) => ({
  color: theme.palette.common.white,
  textTransform: "uppercase",
  fontWeight: "800",
  fontSize: "50px",
  textAlign: "center",
  marginBottom: theme.spacing(5),
}));

const SvgDecoration = styled(Box)({
  backgroundPositionY: "center",
  backgroundPositionX: "right",
  backgroundRepeat: "no-repeat",
  backgroundImage: `url(./hexagonal.svg)`,
  width: "100%",
  position: "absolute",
  height: "600px",
  zIndex: -1,
});

const BoxBadgeTypes = styled(Box)({
  marginTop: "10%",
  marginBottom: "10%",
  padding: "5%",
  display: "flex",
  flexDirection: "column",
  flex: 1,
  background: "rgba(0, 0, 0, 0.58)",
  borderRadius: "10px",
});

export default function Home() {
  return (
    <Box>
      <Box mt={8}>
        <SvgDecoration />
        <Box>
          <TheBadgeTitle>The Badge,</TheBadgeTitle>
          <TheBadgeSubTitle>
            Information certification <br /> & profile identity
          </TheBadgeSubTitle>
        </Box>
        <Paragraph>
          The Badge is a decentralized certification platform built on Ethereum
          that allows tokenizing on any piece of information coming either
          on-chain or off-chain under the concept of badges. These badges will
          create an on chain identity by being issued as non-transferable and
          verifiable NFTs.
        </Paragraph>
      </Box>
      <BoxBadgeTypes>
        <TypesTitle>Types of badges</TypesTitle>

        <BadgeTypeDescription
          tittle={"On-chain \n Badges"}
          body={`These badges are created by generating a query to 
          a subgraph from The Graph. These queries will confirm which 
          addresses have the characteristics needed to receive a specific badge.`}
          image={svg1}
        />

        <BadgeTypeDescription
          tittle={"Off-chain \n Badges"}
          body={`These badges are the tokenization of real world information.
          It could be diplomas, passports, social media accounts, etc. Before the badge is 
          created, the document/ information needs to be verified by Kleros court.`}
          image={svg2}
        />

        <BadgeTypeDescription
          tittle={"Third-party \n Badges"}
          body={`These are badges that can be generated by a public or private entity,
           and there will be no data verification process. The third party will be able 
           to determine what is on their badge, and The Badge will distribute it to 
           pre-determined addresses.`}
          image={svg3}
        />
      </BoxBadgeTypes>
    </Box>
  );
}
